### PR TITLE
Event-level plotting of glmtools datasets

### PR DESCRIPTION
**Pull request by wx4stg**

### CODE REVIEW

**Comment by wx4stg** [comment]
so I closed #40 and tried reopening here because GH actions weren't running... only to realize actions are down at the moment.. 
image

**Comment by wx4stg** [comment]
Add parallax correction, make the cross sect vlines and user-config heights

**Comment by wx4stg** [comment]
not to hate on the europeans or anything--but why is sweep angle 'y' the default for geostationary fixed grid system

https://github.com/deeplycloudy/xlma-python/blob/f392af2f43104c3aae558745df40eee0c9e1a14a/pyxlma/coords.py#L208

I'm pretty sure most users of this so-called "library" are US-based

**Comment by wx4stg** [comment]
Intentionally didn't update tests to highlight differences between corrected and uncorrected images. Overall points near Lubbock move to the south and slightly west. This seems backwards from my understanding...

corrected
uncorrected

baseline
result-failed-diff
result

**Comment by wx4stg** [comment]
The shift from parallax correction isn't really all that much, and switching from cartopy transforms to using coords.py seems to have done a lot more damage, somehow...

parallax corrected, coords.py, with LMA points:
corrected

No correction, coords.py, with LMA points:
uncorrected

**Comment by wx4stg** [comment]
LCFA lat/lon are already parallax corrected, compare the output of this to the 'truth'

**Comment by wx4stg** [comment]
image
image
well that's not great

**Comment by wx4stg** [comment]
allow ellipse kwarg in coords.GeostationaryFixedGridSystem's init to be a tuple

**Comment by wx4stg** [comment]
image

red dots are the delivered lat/lons

**Comment by deeplycloudy** [comment]
Reviewed, looks good to me!

**Pull request merged**
